package semesterprojektf19.domain;

public enum TargetAreas {
    PHYSICAL_DISABILITY, MENTAL_DISABILITY, SOCIAL_PROBLEM,
    PRACTICAL_TASKS_AT_HOME, SELFCARE, MOBILITY, COMMUNICATION,
    COMMUNITY_LIFE, SOCIAL_LIFE, HEALTH, ENVIRONMENT;

}
